version: '3.9'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./nginx/ssl:/etc/nginx/ssl"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "443:443"
      - "80:80"
    links:
      - nexus
    depends_on:
      - nexus
  nexus:
    image: sonatype/nexus3:3.36.0
    container_name: nexus
    volumes:
      - "./data:/nexus-data"
    # - "./deploy:/opt/sonatype/nexus/deploy"

